### ISSUE TITLE
Porting?

### ISSUE THREAD

**Issue by muhdmirzamz** [The-Brothers/ClickColor#14]
Does this game run on a mac? If it does not, I can use xcode and just try my best to make it on a mac, if you'd like :)

**Comment by leonn** [comment]
We don't have a mac to test, so we don't know if it run on mac, would be nice if you could test and make a Port. Currently i'm working on porting to PS3.

**Comment by athos-ribeiro** [comment]
If you get it to work, please do it and send us the merge request! You can
also add instructions in the README file! Thank you!

**Comment by muhdmirzamz** [comment]
Sure do :)

**Comment by muhdmirzamz** [comment]
I have to try first. And by running on a mac, I mean, just through SDL window. Not in the mac appstore or anything :) Im just trying here. So, I will keep you guys updated

**Comment by runys** [comment]
Hey man! Thanks for stoping by! Here we have some info about the project: http://the-brothers.github.io/ClickColor/

Feel free to port it to Mac. Currently we don't have any Mac computer avaible, so all the help is welcome :D

**Comment by muhdmirzamz** [comment]
I just realised the project is not based on the latest version of SDL. I personally don't know any objective c but I can help you test on a mac. I have some experience developing with SDL2.0. I can update the files too:)

**Comment by runys** [comment]
Yep. This this project started at early 2013, when SDL2.0 was only a dream. Feel free to update to SDL2.0 and do a pull request when its done.

About the Objective C, dont worry about it. The whole project is written in C++.

**Comment by muhdmirzamz** [comment]
Game works on mac now. I've fixed the bugs. But, timer still not ported though.

**Comment by leonn** [comment]
merge porting already
